### ISSUE TITLE
Use of threading casues crashes in Blender:

### ISSUE THREAD

**Issue by ideasman42** [AIGODLIKE/Colorista#5]
This extensions is using `threading` which isn't supported by Blender and can cause random crashes.

See: https://projects.blender.org/blender/blender/issues/130386#issuecomment-1352657

**Comment by Yorha4D** [comment]
@ideasman42 I noticed this issue, but
1. The add-on only loads node groups
2. These node groups are all using Blender nodes
3. The reason for the problem is that the rendering initialization failed, and using GPU would not cause this issue
This should be a fault of Blender 4.3 version itself.
But no matter what, this has caused the problem, and I will continue to track this malfunction

**Comment by ideasman42** [comment]
@Yorha4D `./utils/watcher.py` uses `threading`.

**Comment by KarryCharon** [comment]
> @Yorha4D `./utils/watcher.py` uses `threading`.

This module is working for file changing detection. Nothing about blender.

**Comment by Yorha4D** [comment]
@ideasman42 Switch threading to timer

**Comment by ideasman42** [comment]
> > @Yorha4D `./utils/watcher.py` uses `threading`.
> 
> This module is working for file changing detection. Nothing about blender.

It's running inside Blender, which is enough to cause crashes.

**Comment by KarryCharon** [comment]
> > > @Yorha4D `./utils/watcher.py` uses `threading`.
> > 
> > 
> > This module is working for file changing detection. Nothing about blender.
> 
> It's running inside Blender, which is enough to cause crashes.

Yep, we've changed threading to timer to impl the fs detection, you can try again.
